### ISSUE TITLE
请问有关于chika_account.json的说明吗

### ISSUE THREAD

**Issue by NepPure** [Kengxxiao/Chika#1]
非常感谢

**Comment by Kengxxiao** [comment]
chika_account内是一个jarray 其中每个jobject是/tool/sdk_login接口请求的uid, access_key, ~~viewer_id~~（最新的commit里已经不需要了）的集合
用来第一次启动时载入账号信息，之后便不需要该文件的内容
如果该文件中某个已经录入的账号数据被修改，则会在启动时修改已经录入的数据

**Comment by NepPure** [comment]
第一次用的时候他可以是空的是吧

**Comment by Kengxxiao** [comment]
可以是```[]```
但是需要至少两个账号Chika才会完整运行

**Comment by NepPure** [comment]
啊 感谢大佬解答，大概明白了，这是填写用于请求数据的账号信息，大佬这里有获得这些信息的教程么，是不是需要root过的模拟器，游客账号是否可行

**Comment by Kengxxiao** [comment]
我目前的做法是手动过一遍geetest的验证码 用Fiddler抓包 通过CryptAES::DecryptRJ256Api解密数据获得msgpack 序列化成json后填进chika_account里

**Comment by NepPure** [comment]
感谢大佬 学废了！
