### ISSUE TITLE
大佬你好！

### ISSUE THREAD

**Issue by nksolo** [Kengxxiao/Chika#2]
大佬你好！我最近也在深入了解相关拆包技术但是我遇到了一些问题，
我在明日方舟拆包(使用AssetStudioGUI)的过程中部分文本文件无法正常解包，显示乱码（隐约可以看到UNITY FS）
因此我想求问一下您的解包方法(使用了什么软件)，如您库中ArknightsGameData/zh_CN/gamedata/excel/character_table.json是如何生成的。
我的联系方式2574825441@qq.com

**Comment by Jalchemist33** [comment]
大佬在吗？我也对这一部分比较感兴趣，貌似这一个文件的解密方式与同路径下的其他文件不同，也麻烦您解答一下：
happyjalch42@outlook.com
