### ISSUE TITLE
非项目问题，有疑问

### ISSUE THREAD

**Issue by Kudryavka03** [Kengxxiao/Chika#3]
最近我在尝试抓EN服的会战数据，但是/checkagreement就遇到了问题。
我不清楚他是如何工作的，参考其他项目和您的Chika，应该按道理取发包最后32个字符作为key，发送头DEVICE-ID作为向量，尝试解密，但解密程序出错。如果解密响应数据的话，解密程序则不会出错，但解密的数据是乱码，是我做错了什么吗》期待大佬回答

**Comment by Kudryavka03** [comment]
如果忙或者其他原因解答不能就close，但我还是希望能解答一下或者哪天吧EN服的数据并入您那个会战数据网站就最好了

**Comment by Kengxxiao** [comment]
乱码应该是初始向量的问题  
只有国服有一个IVString作为初始向量 其他服务器都是UDID[..16]  
![image](https://user-images.githubusercontent.com/11478651/113558295-fb620100-9631-11eb-9ac5-e1cbdab3fc04.png)
  
可以的话，麻烦提交一份base64编码的请求响应数据（

**Comment by Kudryavka03** [comment]
感谢回答，目前解决了
